version: "3.6"

services:
  webscraper:
    build:
      dockerfile: docker/arm32v7/Dockerfile
      context: ./
      args:
        TZ: Europe/Moscow
    volumes:
      - "./config:/home/webscraper/app/config"
      - "./.env:/home/webscraper/app/.env"
      - "./logs:/home/webscraper/app/logs"
      - "./download:/home/webscraper/app/download"
    networks:
      - webscraper
    mem_limit: 1664m
    mem_reservation: 512M
    cpus: 0.5

networks:
  webscraper:
    driver: bridge
